QuantUtilitiesMongoRouterBundle_admin_index:
  pattern: /
  defaults: {_controller: QuantUtilitiesMongoRouterBundle:Admin:index}
QuantUtilitiesMongoRouterBundle_admin_addroute:
  pattern: /route/add
  defaults: {_controller: QuantUtilitiesMongoRouterBundle:Admin:addRoute}
QuantUtilitiesMongoRouterBundle_admin_createroute:
  pattern: /route/create
  defaults: {_controller: QuantUtilitiesMongoRouterBundle:Admin:createRoute}
  requirements: {_method: post}
QuantUtilitiesMongoRouterBundle_admin_delete:
  pattern:  /route/{id}/truncate
  defaults: {_controller: QuantUtilitiesMongoRouterBundle:Admin:deleteRoute}