home:
  pattern: /
  defaults: {_controller: QuantUtilitiesMongoRouterBundle:Admin:index}

# test:
#   pattern: /{something}/hello
#   defaults: {_controller: QuantUtilitiesMongoRouterBundle:Admin:index}

#quant_utilities_mongorouter_cached:
#    prefix: /
#    resource: ""

quant_utilities_mongo_router:
    resource: "@QuantUtilitiesMongoRouterBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal